# -*- coding: utf-8 -*-
"""ProyectoLeetCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jAoBaSbGSMkV0UmzdDSDavCgTW3sL4mI
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("gzipchrist/leetcode-problem-dataset")

print("Path to dataset files:", path)

import os
print(os.listdir(path))

import pandas as pd

import numpy as np

"""VISUALIZAR"""

# VISUALIZAR

from google.colab import data_table

# 1. CARGAR DATOS (Recuperamos el código de tu captura)
# Asumiendo que 'path' ya está definido por la celda de arriba.
# Si 'path' también te da error, vuelve a ejecutar la celda de "kagglehub".
archivo_csv = os.path.join(path, 'leetcode_dataset - lc.csv')
df = pd.read_csv(archivo_csv)

# 2. VISUALIZAR
data_table.enable_dataframe_formatter()
display(df)

# 1. Definimos la lista de columnas que quieres conservar
columnas_seleccionadas = [
    'id',
    'title',
    'description',
    'difficulty',
    'related_topics',
    'similar_questions'
]

df_limpio = df[columnas_seleccionadas].copy()
df_limpio['related_topics'] = df_limpio['related_topics'].fillna("Sin temas")
df_limpio['similar_questions'] = df_limpio['similar_questions'].fillna("[]")


# 3. Visualizamos el resultado
print(f"Dimensiones del nuevo dataset: {df_limpio.shape}")
display(df_limpio.head())

"""TOKENIZAR DIFICULTADES"""

mapa_dificultad = {'Easy': 1, 'Medium': 2, 'Hard': 3}
df_limpio['difficulty_score'] = df_limpio['difficulty'].map(mapa_dificultad)

df_limpio['difficulty_score']
df_limpio = df_limpio.drop(columns=["difficulty"])

df_limpio

"""
EMBEDDING"""

from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

columsEMB = ['title', 'description', 'related_topics', 'similar_questions']
df_limpio[columsEMB] = df_limpio[columsEMB].fillna('')

def unificarTexto(row):
    partes = []

    if pd.notna(row['title']):
        partes.append(f"TITULO: {row['title']}")

    if pd.notna(row['description']):
        partes.append(f"DESCRIPCION: {row['description']}")

    if pd.notna(row['related_topics']):
        partes.append(f"TEMAS: {row['related_topics']}")

    if pd.notna(row['similar_questions']):
        partes.append(f"PREGUNTAS SIMILARES: {row['similar_questions']}")

    return "\n".join(partes)

"""APLICAR EMBEDDING"""

df_limpio['text_for_embedding'] = df_limpio.apply(unificarTexto, axis=1)

df_limpio['text_for_embedding'] = df_limpio['text_for_embedding'].str.lower().str.strip()

embeddings = model.encode(df_limpio['text_for_embedding'].tolist(), show_progress_bar=True)


np.save("embeddings.npy", embeddings)
df_limpio.drop(columns=['text_for_embedding']).to_csv("metadata_problemas.csv", index=False)

"""SIMILITUD COSENO

"""

from sklearn.metrics.pairwise import cosine_similarity

def problemas_similares(
    df,
    embeddings,
    problem_id,
    top_k=5
):

    idx = df.index[df["id"] == problem_id][0]
    query_embedding = embeddings[idx].reshape(1, -1)


    similarities = cosine_similarity(query_embedding, embeddings)[0]

    df_tmp = df.copy()
    df_tmp["similarity"] = similarities

    df_tmp = df_tmp[df_tmp["id"] != problem_id]

    resultados = df_tmp.sort_values(
        "similarity",
        ascending=False
    ).head(top_k)


    resultados = resultados.sort_values("difficulty_score")

    return resultados[
        ["id", "title", "difficulty_score", "similarity"]
    ]

resultados = problemas_similares(
    df_limpio,
    embeddings,
    problem_id=int(input("Indica que ejercicio quieres 1-1825")),
    top_k=5
)


print(resultados)